name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_files:
    name: Check Modified Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.event.pull_request.head.ref }}  # Checkout the code from the source branch of the pull request

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y grep
      
      - name: branch name
        run: git branch | grep "*"

      - name: Get list of modified files
        id: get_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }})"

      - name: Check for required functions
        run: |
          for file in ${{ steps.get_files.outputs.files }}; do
            # Check if the file ends with "-playbook.sh"
            if echo "$file" | grep -q '\-playbook\.sh$'; then
              if grep -qE "function (__besman_init|__besman_execute|__besman_prepare|__besman_publish|__besman_cleanup)" "$file"; then
                echo "All required functions found in $file"
              else
                echo "One or more required functions not found in $file"
                exit 1
              fi
            fi
          done
